Unify travis tab-style (4 spaces)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,77 +2,76 @@ sudo: false
 language: cpp
 
 os:
-  - linux
+    - linux
 
 compiler:
-  - clang
-  - g++
+    - clang
+    - g++
 
 env:
-  - BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
-  - BUILD_TYPE=Debug CXX_FLAGS=-std=c++11
-  - BUILD_TYPE=Release CXX_FLAGS=-std=c++03
-  - BUILD_TYPE=Release CXX_FLAGS=-std=c++11
+    - BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
+    - BUILD_TYPE=Debug CXX_FLAGS=-std=c++11
+    - BUILD_TYPE=Release CXX_FLAGS=-std=c++03
+    - BUILD_TYPE=Release CXX_FLAGS=-std=c++11
 
 addons:
-  apt:
-    sources:
-      - boost-latest
-      - ubuntu-toolchain-r-test
-    packages:
-      - libboost1.55-all-dev
-      - g++-4.8
-      - cmake
-      - libsdl1.2-dev
-      - libsdl-mixer1.2-dev
-      - libcurl4-openssl-dev
-      - libbz2-dev
-      - libminiupnpc-dev
-      - liblua5.2-dev
-      
+    apt:
+        sources:
+            - boost-latest
+            - ubuntu-toolchain-r-test
+        packages:
+            - libboost1.55-all-dev
+            - g++-4.8
+            - cmake
+            - libsdl1.2-dev
+            - libsdl-mixer1.2-dev
+            - libcurl4-openssl-dev
+            - libbz2-dev
+            - libminiupnpc-dev
+            - liblua5.2-dev
+            
 matrix:
-  include:
-    - os: osx
-      compiler: clang
-      install:
-        - brew update
-        - brew install sdl
-        - brew install sdl_mixer
-        - brew install gettext
-        - brew install miniupnpc
-        - brew link --force gettext
-      env: BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
-  exclude:
-    - compiler: clang
-      env: BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
-    - compiler: clang
-      env: BUILD_TYPE=Release CXX_FLAGS=-std=c++03      
+    include:
+        - os: osx
+          compiler: clang
+          install:
+              - brew update
+              - brew install sdl
+              - brew install sdl_mixer
+              - brew install gettext
+              - brew install miniupnpc
+              - brew link --force gettext
+          env: BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
+    exclude:
+        - compiler: clang
+          env: BUILD_TYPE=Debug CXX_FLAGS=-std=c++03
+        - compiler: clang
+          env: BUILD_TYPE=Release CXX_FLAGS=-std=c++03            
 
 install:
-  # C++11 requires gcc-4.8 or newer
-  - if [ "$CXX" = "g++" ] && [ "$CXX_FLAGS" = "-std=c++11" ]; then export CXX="g++-4.8"; fi
-  - |
-	if [ "$CXX" = "g++" ]; then
-		# Adapt gcc and gcov version by simply replacing the prefix "g++"
-		export CC=${CXX/g++/gcc}
-		export GCOV=${CXX/g++/gcov};
-	else
-		export GCOV="gcov"
-	fi
-  # Travis libs are x64 only
-  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export ADDITIONAL_CMAKE_FLAGS="--no-arch=i386"; fi
+    # C++11 requires gcc-4.8 or newer
+    - if [ "$CXX" = "g++" ] && [ "$CXX_FLAGS" = "-std=c++11" ]; then export CXX="g++-4.8"; fi
+    - |
+        if [ "$CXX" = "g++" ]; then
+            # Adapt gcc and gcov version by simply replacing the prefix "g++"
+            export CC=${CXX/g++/gcc}
+            export GCOV=${CXX/g++/gcov};
+        else
+            export GCOV="gcov"
+        fi
+    # Travis libs are x64 only
+    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export ADDITIONAL_CMAKE_FLAGS="--no-arch=i386"; fi
 
 script:
-  # Fail if any command failed
-  - set -e
-  - cd build
-  - ./cmake.sh --RTTR_PREFIX=. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" --generator="Unix Makefiles" ${ADDITIONAL_CMAKE_FLAGS}
-  - make
-  # Execute tests
-  - export CTEST_OUTPUT_ON_FAILURE=1
-  - make test
-  - set +e
+    # Fail if any command failed
+    - set -e
+    - cd build
+    - ./cmake.sh --RTTR_PREFIX=. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" --generator="Unix Makefiles" ${ADDITIONAL_CMAKE_FLAGS}
+    - make
+    # Execute tests
+    - export CTEST_OUTPUT_ON_FAILURE=1
+    - make test
+    - set +e
 
 after_success:
-  - bash <(curl -s https://codecov.io/bash) -x "${GCOV}"
-
+    - bash <(curl -s https://codecov.io/bash) -x "${GCOV}"
